name: xChanger Build PipeLine
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking Out
      uses: actions/checkout@v2
    - name: Setting Up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
        include-prerelease: false
    - name: ' Restoring Nuget Packages'
      run: dotnet restore
    - name: ' Building Project'
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
